/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ramesh' at '25/5/17 10:57 AM' with Gradle 2.10
 *
 * @author ramesh, @date 25/5/17 10:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
